### ISSUE TITLE
Команда vote

### ISSUE THREAD

**Issue by 357max357** [corradowaver/discord-bot-guild-girl-kt#12]
Описание ошибки
> При вызове команды vote и игнорировании голосования выводит NaN.

Шаги по воспроизведению ошибки
> Вызов команды vote с используемым префиксом на данный момент.
> Не выбирать вариант голосования.

**Comment by corradowaver** [comment]
Thanks for reporting! fixed in commit "f562cf19d2b9bf904fa25a18954ecccc2e897be2"
