### ISSUE TITLE
Приветствие бота

### ISSUE THREAD

**Issue by 357max357** [corradowaver/discord-bot-guild-girl-kt#13]
Описание ошибки
> При вызове любой голосовой команды, бот подключается к каналу в Disrord и включает приветствие для себя.

Шаги по воспроизведению ошибки
> Находится в Discord и быть подключенным к каналу.
> Вызов любой голосовой команды в текстовом чате.

**Comment by corradowaver** [comment]
Thanks for reporting! Solved with https://github.com/corradowaver/discord-bot-guild-girl-kt/pull/15
