### ISSUE TITLE
Команда joke, проблема присоединения бота

### ISSUE THREAD

**Issue by 357max357** [corradowaver/discord-bot-guild-girl-kt#16]
Описание ошибки
> При вызове команды joke, бот присоединяется к первому по списку каналу, а не в тот, где находится написавший команду.

Шаги по воспроизведению ошибки
> Перейти в любой канал, ниже первого.
> Вызвать команду joke

**Comment by corradowaver** [comment]
Thanks for reporting! Fixed in commit "c58307ba62e3184221f35fbb7488b6f9e26907ad"
